name: main

on:
  push:
    branches: [master, own]
  pull_request:
    branches: [master, own]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn
      - run: yarn prettier --ignore-path .gitignore --check .

      - run: yarn build
      # Need tests plz
      # - run: yarn workspace @mckayla/electron-redux-e2e test
